In [ ]:
import cv2
import numpy as np

url = "http://192.168.226.189:8080/video" #camera tel
VideoCap = cv2.VideoCapture(url)

lo=np.array([95,80,60])
hi=np.array([115,255,255])

def detect_inrange(image,min,max):
    points=[]
    image=cv2.blur(image,(5,5))

    image = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(image, lo , hi)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, None,iterations = 2)
    elements = cv2.findContours(
        mask,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)[-2]
    
    elements=sorted(elements,key=lambda x:cv2.contourArea(x), reverse=True)

    for element in elements:
        if int(cv2.contourArea(element)) > min & int(cv2.contourArea(element)) < max:
            ((x,y), rayon) = cv2.minEnclosingCircle(element)
            points.append(np.array([int(x), int(y), int(rayon), int(cv2.contourArea(element))]))
    
    return image,mask,points

if not VideoCap.isOpened():
    print("error capture")
    exit(0)

while(True):
    ret, frame = VideoCap.read()

    frame = cv2.resize(frame, (640, 480))

    if not ret:
        print("error read frame")
        break
    
    cv2.flip(frame,1,frame)

    image,mask,points = detect_inrange(frame,1000,3000)
    cv2.circle(frame,(100,100),20,(0,255,0),5)
    print(image[100,100])

    if(len(points)>0):
        cv2.circle(frame,(points[0][0],points[0][1]), points[0][2], (0,0,255), 2)
        cv2.putText(frame,str(points[0][3]),(points[0][0],points[0][1]),
                    cv2.FONT_HERSHEY_COMPLEX,1,(255,0,0),2,cv2.LINE_AA)
    
    if mask is not None:
        cv2.imshow("mask",mask)
    
    cv2.imshow("image",frame)

    if cv2.waitKey(10) &0XFF == ord('q'):
        break

VideoCap.release()
cv2.destroyAllWindows()





[ 26  64 219]
[ 23  74 213]
[ 24  80 211]
[ 23 119 174]
[ 34  60 128]
[ 45  32 128]
[ 29  93 118]
[ 23 140 157]
[ 22 143 160]
[ 22 141 168]
[ 23 141 168]
[ 23 142 165]
[ 23 140 160]
[ 22 152 159]
[ 22 145 163]
[ 22  99 213]
[ 22 108 205]
[ 22 116 192]
[ 22 120 193]
[ 22 120 194]
[ 22 122 195]
[ 21 122 196]
[ 21 111 206]
[ 21 107 205]
[ 22 110 208]
[ 21 109 210]
[ 21 113 216]
[ 21 113 215]
[ 21 118 214]
[ 21 111 219]
[ 21 101 219]
[ 21  99 217]
[ 20  95 218]
[ 23  82 236]
[ 23  82 236]
[ 23  82 237]
[ 23  80 238]
[ 23  80 238]
[ 23  80 238]
[ 21  94 227]
[ 21  94 229]
[ 21  94 227]
[ 21  85 227]
[ 22  86 157]
[ 36  44 117]
[ 36  35 118]
[ 26  83 135]
[ 24  76 138]
[ 22  95 161]
[ 20  96 181]
[ 20  88 176]
[ 20  85 216]
[ 20  83 218]
[ 20  82 234]
[ 20  85 252]
[ 20  88 251]
[ 21 112 242]
[ 22  84 237]
[ 22  87 238]
[ 21 113 210]
[ 22 148 193]
[ 21 139 180]
[ 21 129 184]
[ 21 110 195]
[93 70 95]
[ 20  96 149]
[100  99 142]
[ 99  93 137]
[ 86  41 137]
[ 87  33 141]
[ 81  34 142]
[ 81  34 