In [ ]:
import cv2
import numpy as np



# Lire l'image
image_path = '../img.jfif'
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
cv2.threshold(img,128,255,cv2.THRESH_BINARY,img)
cv2.namedWindow("erode")
sizeErode = 1

def erode_func():
    size = sizeErode*2 +1
    kernel = cv2.getStructuringElement(cv2.MORPH_CROSS,(size,size))
    print(kernel)
    img_erode = cv2.erode(img,kernel)
    cv2.imshow("erode",img_erode)

    cv2.erode(img,)
def changeESize(x):
    global sizeErode
    sizeErode = x
    erode_func() 

cv2.createTrackbar("erodSize","erode",sizeErode,17,changeESize)

cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np



# Lire l'image
image_path = '../img.jfif'
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
cv2.threshold(img,128,255,cv2.THRESH_BINARY,img)
cv2.namedWindow("dilate")
sizeDilate = 1

def erode_func():
    size = sizeDilate*2 +1
    kernel = cv2.getStructuringElement(cv2.MORPH_CROSS,(size,size))
    print(kernel)
    img_dilate = cv2.dilate(img,kernel)
    cv2.imshow("dilate",img_dilate)

    cv2.erode(img,)
def changeESize(x):
    global sizeDilate
    sizeDilate = x
    erode_func() 

cv2.createTrackbar("dilateSize","dilate",sizeDilate,17,changeESize)

cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np



# Lire l'image
image_path = '../img.jfif'
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
cv2.threshold(img,128,255,cv2.THRESH_BINARY,img)
cv2.namedWindow("morph")
sizeMorph= 1

def morph_func():
    size = sizeMorph*2 +1
    kernel = cv2.getStructuringElement(cv2.MORPH_CROSS,(size,size))
    print(kernel)
    img_morph = cv2.morphologyEx(img,cv2.MORPH_GRADIENT,kernel)
    cv2.imshow("morph",img_morph)


def changeSize(x):
    global sizeMorph
    sizeMorph = x
    morph_func() 

cv2.createTrackbar("morphSize","morph",sizeMorph,17,changeSize)

cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 1 0]
 [1 1 1]
 [0 1 0]]


error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'erode'
> Overload resolution failed:
>  - erode() missing required argument 'kernel' (pos 2)
>  - erode() missing required argument 'kernel' (pos 2)
